services:
  siteproxy:
    image: node:21
    container_name: siteproxy-node
    restart: unless-stopped
    ports:
      - 127.0.0.1:5006:5006
    volumes:
      - ../:/home/node/siteproxy/
    working_dir: /home/node/siteproxy/
    entrypoint: ["node","/home/node/siteproxy/bundle.js"]
